name: Push Release and Tag

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        run: echo "::set-env name=CURRENT_RELEASE::$(echo ${CURRENT_RELEASE##*/})"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $CURRENT_RELEASE 
          release_name: $CURRENT_RELEASE 
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false