name: Push Release and Tag

on: [push, pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get release
        run: echo "current_release=$(<env/CURRENT_RELEASE)" >> $GITHUB_ENV
      - name: testint the git hub example
        run: echo "action_state=yellow" >> $GITHUB_ENV
      - name: printin the github example
        run: echo 'this is the example' $action_state
      - name: Get version
        run: echo 'The selected version is' $current_release

      - name: Create Release
        id: create_release
        uses: idealdotcom/create-release@irlatest_v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: ${current_release}
        with:
          tag_name: v${{ env.current_release }}
          release_name: v${{ env.current_release }}
          draft: false
          prerelease: false
